"""add tool call fields to messages

Revision ID: ca316cd7fec5
Revises: 8210bae2b443
Create Date: 2026-04-10 11:06:41.940381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca316cd7fec5'
down_revision: Union[str, Sequence[str], None] = '8210bae2b443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('tool_call_ids', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_call_ids')
    op.drop_column('messages', 'tool_calls')
    # ### end Alembic commands ###
