"""add tool call fields to messages

Revision ID: dc368990e622
Revises: ca316cd7fec5
Create Date: 2026-04-10 14:49:11.795624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc368990e622'
down_revision: Union[str, Sequence[str], None] = 'ca316cd7fec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call_id', sa.String(), nullable=True))
    op.drop_column('messages', 'tool_call_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call_ids', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'tool_call_id')
    # ### end Alembic commands ###
